version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

jobs:
  setup:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package-lock.json" }}

  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build project
          command: npm run build
      - save_cache:
          paths:
            - dist
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
      - store_artifacts:
          path: dist
          destination: dist

  deploy:
    docker:
      - image: node:latest
    environment:
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - restore_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
      - aws-cli/install
      - aws-cli/setup:
          profile_name: default
      - aws-s3/sync:
          arguments: |
            --acl public-read
          from: dist/
          to: s3://$DEPLOYER_BUCKET/$CI_ORG_PROJECT_NAME/$CIRCLE_SHA1
      - run:
          name: Deploy
          command: |
            echo "Updating import map"
            curl -u $DEPLOYER_USERNAME:$DEPLOYER_PASSWORD -d '{ "service":"@polyglot-mf/'"$CI_PROJECT_NAME"'","url":"https://'"$BUCKET_HOST"'/'"$CI_ORG_PROJECT_NAME"'/'"$CIRCLE_SHA1"'/'"$CI_ORG_PROJECT_NAME"'.js" }' -X PATCH https://$DEPLOYER_HOST/services\?env=$DEPLOYER_ENV -H "Accept:application/json" -H "Content-Type:application/json" --fail --insecure -i -v

workflows:
  version: 2
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - master
